### ISSUE TITLE
How come prior probability distribution over z is greater than 1?

### ISSUE THREAD

**Issue by posutsai** [openias/openias.github.io#4]
I was reading your post [variational coin toss](http://www.openias.org/variational-coin-toss). It really helps me a lot in studying variational inference. But I am confused about your description of prior probability distribution over z. Especially in graph plot beta distribution Beta(α=3,β=3) which is chosen by us.
![prior probability distribution of z](http://www.openias.org/img/variational-coin-prior.png)
So I think if there is any misunderstand about prior distribution maybe you can help me on this. In my comprehension, z represent the probability of either the coin is head or tail. It is easy to realize that z     should have less chance to be near 1 or 0, and more opportunity to close to 0.5. However the probability of z can't be greater than 1 no matter how high it is. In plot, when z is 0.5, p(z) is almost 1.75. Is this result reasonable? Or maybe it should to be normalized, for integrating to 1.

**Comment by openias** [comment]
Sorry for the late reply. I didn't get a notification. The answer to your question is that the prior distribution is a probability *density* function. It's the surface under the curve between two z points that describes the probability that z is in that range. It takes some time to get used to, but it's a very good way of describing probabilities over continuous variables. Hope it helps!
